---
- name: Install ntp
  yum: name=ntp state=installed

- name: Install ntpdate
  yum: name=ntpdate state=installed

- service: name=ntpd enabled=yes state=restarted

- name: Install mc
  yum: pkg=mc state=installed

- name: change SElinux policy to permissive
  template: src=selinux_config.j2 dest=/etc/selinux/config owner=root group=root mode=0600
  
- command: setenforce 0

- name: prepare iptables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root group=root mode=0644
  notify: restart iptables
