---
- name: Install and configure Redis
  yum: pkg=redis state=installed

- template: src=redis.conf.j2 dest=/etc/redis.conf owner=root group=root mode=0644

- service: name=redis enabled=on state=restarted